### ISSUE TITLE
Auto-save failures

### ISSUE THREAD

**Issue by bjones1** [bjones1/CodeChat_Editor#28]
Auto-save doesn't work when the edit made was through the TinyMCE GUI (for example, updating a hyperlink, changing a font, etc.).

**Comment by Akame-Ga-Kill** [comment]
Observed this also when trying to save on the server colors associated with it.

**Comment by bjones1** [comment]
> Observed this also when trying to save on the server colors associated with it.

Thanks for the report. Does auto-save work if you then type something in the same doc block?

Some background: CodeMirror is an IDE for the browser, which I use for the CodeChat Editor. Inside CodeMirror, I embed TinyMCE to do the GUI editing of HTML. TinyMCE then needs to save any modifications it makes back into CodeMirror data structures, which the CodeChat Editor then saves to disk. However, my code instead listens for keystrokes and updates the CodeMirror data structures from TinyMCE, but doesn't respond to mouse clicks, etc. Instead, it should (probably) [listen](https://www.tiny.cloud/docs/tinymce/latest/apis/tinymce.editor/#on) for a TinyMCE `dirty` event (see [editor core events](https://www.tiny.cloud/docs/tinymce/latest/events/#editor-core-events)), then [clear the `dirty`](https://www.tiny.cloud/docs/tinymce/latest/apis/tinymce.editor/#setDirty) flag when the CodeMirror data structure is updated.

How how the system currently works: in my [EditorView](https://codemirror.net/docs/ref/#view.EditorView) [plugin](https://codemirror.net/docs/ref/#view.EditorView.plugin), which is a [ViewPlugin](https://codemirror.net/docs/ref/#view.EditorView.plugin) which implements a [PluginSpec](https://codemirror.net/docs/ref/#view.PluginSpec), I define [event observers](https://codemirror.net/docs/ref/#view.PluginSpec.eventObservers). One of these event observers watches for an [input](https://developer.mozilla.org/en-US/docs/Web/API/Element/input_event) event (see below), which responds to keyboard input by updating the document (all code/doc blocks). 

An autosave CodeMirror extension responds to these changes by starting and autosave timer, when then saves the files.

## Input event observer
https://github.com/bjones1/CodeChat_Editor/blob/41dd3de1a847e33782ccab363be1b19b2e2021d9/client/src/CodeMirror-integration.mts#L550-L578

## CodeMirror event handler
https://github.com/bjones1/CodeChat_Editor/blob/41dd3de1a847e33782ccab363be1b19b2e2021d9/client/src/CodeChatEditor.mts#L199-L201

## Autosave extension
https://github.com/bjones1/CodeChat_Editor/blob/41dd3de1a847e33782ccab363be1b19b2e2021d9/client/src/CodeChatEditor.mts#L215-L217

https://github.com/bjones1/CodeChat_Editor/blob/41dd3de1a847e33782ccab363be1b19b2e2021d9/client/src/CodeChatEditor.mts#L349-L390

**Comment by bjones1** [comment]
Fixed in 6a93076eae09fb4e19224b60826d0e01cfe8d054.
