### ISSUE TITLE
The error Property 'editor_to_code_doc_blocks' does not exist on type '{ EditorMode: typeof EditorMode; open_lp

### ISSUE THREAD

**Issue by Akame-Ga-Kill** [bjones1/CodeChat_Editor#34]
Theerror Property 'editor_to_code_doc_blocks' does not exist on type '{ EditorMode: typeof EditorMode; open_lp:
(all_source: CodeChatForWeb, editorMode: EditorMode) => void; }'. suggests that editor_to_code_doc_blocks is referenced in your test file, but it’s not part of the exported exportedForTesting object.
Solution:
If editor_to_code_doc_blocks is needed, ensure that it is defined and included in exportedForTesting. If it’s not needed, remove or replace this reference in your test file.
code_doc_block_arr Not Found:

**Comment by bjones1** [comment]
See #34 -- same response.
