### ISSUE TITLE
The error Object literal may only specify known properties, and 'code_doc_block_arr' does not exist in type 'CodeChatForWeb'

### ISSUE THREAD

**Issue by Akame-Ga-Kill** [bjones1/CodeChat_Editor#35]
The error Object literal may only specify known properties, and 'code_doc_block_arr' does not exist in type 'CodeChatForWeb'
. suggests that code_doc_block_arr is not part of the CodeChatForWeb type, which is defined in the CodeChatEditor.mts file.
**Solution:**
If code_doc_block_arr is needed, add it to the CodeChatForWeb type. If it’s not required, remove its reference from your code.

**Comment by bjones1** [comment]
I'm guessing this was an error reported during `npm run build`? If so, it's ignorable; I'll have an update soon with a cleaner build output.
