### ISSUE TITLE
CodeChat Editor shows preivious work's TOC

### ISSUE THREAD

**Issue by tam670** [bjones1/CodeChat_Editor#36]
This is in the VS Code Extension.

I have a project that does not have a TOC.md file. The CodeChat Editor displays the TOC from a different project.

![image](https://github.com/user-attachments/assets/4ab1a3ce-4a22-4de7-a957-1c9311400000)

**Comment by bjones1** [comment]
Tate,

The TOC you see is chosen by looking at the directory the current file is in for TOC.md, then searching the parent directory and so on. So, either put the subdirectory in another location (so the the curernt TOC.md isn't in one of its parents) or add another TOC.md to the current directory.


--
Bryan A. Jones, Ph.D.
Associate Professor
Department of Electrical and Computer Engineering
231 Simrall / PO Box 9571
Mississippi State University
Mississippi State, MS 39762
https://www.ece.msstate.edu/people/faculty/dr-bryan-a-jones/
bjones AT ece DOT msstate DOT edu
voice 662-325-3149
fax 662-325-2298

Our Master, Jesus Christ, is on his way. He'll show up right on
time, his arrival guaranteed by the Blessed and Undisputed Ruler,
High King, High God.
- 1 Tim. 6:14b-15 (The Message)

________________________________
From: Tate Mascari ***@***.***>
Sent: Monday, October 28, 2024 4:42 PM
To: bjones1/CodeChat_Editor ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [bjones1/CodeChat_Editor] CodeChat Editor shows preivious work's TOC (Issue #36)


This is in the VS Code Extension.

I have a project that does not have a TOC.md file. The CodeChat Editor displays the TOC from a different project.

image.png (view on web)<https://github.com/user-attachments/assets/4ab1a3ce-4a22-4de7-a957-1c9311400000>

**Comment by tam670** [comment]
Yes, I just realized that the TOC.md file is actually in the parent directory (Desktop). I will close this ticket.
